version: '3.8'
services:
  backend_dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - HTTP_PROXY=http://8.8.8.8:80
        - HTTPS_PROXY=http://8.8.8.8:443
    dns:
      - 8.8.8.8
      - 8.8.4.4
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./vector_store:/app/vector_store
    networks:
      - app_network
    environment:
      OLLAMA_BASE_URL: http://ollama_dev:11434
      PIP_INDEX_URL: https://pypi.tuna.tsinghua.edu.cn/simple
      PIP_TRUSTED_HOST: pypi.tuna.tsinghua.edu.cn
    tty: true
    stdin_open: true
    
  react_dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env.development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      REACT_APP_URL: http://localhost:3000
      REACT_APP_API_URL: http://localhost:8000
      DISABLE_ESLINT_PLUGIN: "true"
      CI: "false"
      NODE_OPTIONS: "--dns-result-order=ipv4first"
    networks:
      - app_network

  ollama_dev:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/models:/models
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
